[build]
  command = "chmod +x ./build.sh && ./build.sh"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-chromium"

[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"